# Generated by Django 2.2.1 on 2019-05-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0002_auto_20190527_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='editor',
            field=models.ManyToManyField(blank=True, related_name='editor', to='bbs_models.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='bbs_models.Permission'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='bbs_models.Rule'),
        ),
    ]
