# Generated by Django 2.2.1 on 2019-06-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0003_auto_20190527_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='summary',
        ),
    ]
