# Generated by Django 2.2.1 on 2019-06-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0004_remove_topic_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bbs_models.Forum'),
        ),
    ]
