# Generated by Django 2.2.1 on 2019-06-02 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0005_topic_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 6, 2, 11, 35, 38, 610333)),
            preserve_default=False,
        ),
    ]
