# Generated by Django 2.2.1 on 2019-06-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0006_comment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
