# Generated by Django 2.2.1 on 2019-06-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0007_comment_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='floor_count',
            field=models.IntegerField(default=0),
        ),
    ]
