# Generated by Django 2.2.1 on 2019-06-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0008_topic_floor_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='registe_date',
            new_name='register_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/image/avatar/default.gif', upload_to=''),
        ),
    ]
