# Generated by Django 2.2.1 on 2019-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0009_auto_20190604_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/image/avatar/default.gif', upload_to=''),
        ),
    ]
