# Generated by Django 2.2.1 on 2019-06-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0010_auto_20190604_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='url_name',
            field=models.CharField(default='bbs:index', max_length=64),
            preserve_default=False,
        ),
    ]
