# Generated by Django 2.2.1 on 2019-06-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0011_permission_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.IntegerField(choices=[(0, 'all'), (1, 'get'), (2, 'post'), (3, 'put'), (4, 'delete')], default=0),
        ),
    ]
