# Generated by Django 2.2.1 on 2019-06-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0012_auto_20190605_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='Role',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
