# Generated by Django 2.2.1 on 2019-06-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0013_auto_20190605_2128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('url_name', 'action')},
        ),
    ]
