# Generated by Django 2.2.1 on 2019-06-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_models', '0014_auto_20190606_1809'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='permission',
        ),
    ]
